name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull am05/node-cicd-pipeline:latest
      - name: Delete old docker container
        run: sudo docker rm -f node-cicd-pipeline-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name node-cicd-pipeline-container am05/node-cicd-pipeline
